name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Verify the release version"
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: true
          PACKAGE_DIR: ${{ github.workspace }}/custom_components/yandex_speechkit
          PACKAGE_NAME: manifest.json
      - name: "Compress"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/yandex_speechkit"
          zip -r "${{ runner.temp }}/yandex_speechkit.zip" ./
      - name: "Publish"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ runner.temp }}/yandex_speechkit.zip
          body: >
            [![Downloads](https://img.shields.io/github/downloads/black-roland/homeassistant-yandex-speechkit/${{ github.ref_name }}/total?style=flat-square)](https://github.com/black-roland/homeassistant-yandex-speechkit/releases)
            [![Buy me a coffee](https://img.shields.io/badge/buy%20me%20a%20coffee-cc3336?style=flat-square&logo=coffeescript)](https://www.donationalerts.com/r/mansmarthome)
            [![На кофе](https://img.shields.io/badge/%D0%BD%D0%B0%20%D0%BA%D0%BE%D1%84%D0%B5-cc3336?style=flat-square&logo=coffeescript)](https://mansmarthome.info/donate/#donationalerts)
          generate_release_notes: true
